# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 04:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=128)),
                ('group', models.CharField(max_length=32)),
                ('status', models.CharField(max_length=16)),
                ('location', models.CharField(max_length=16)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('last_mod_by', models.CharField(max_length=16)),
            ],
        ),
    ]
